imageV/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .view import HomePage
from auth_app.views import LoginUserView, LogoutView, RegistrationProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name='home-page'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', RegistrationProfileView.as_view(), name='registration'),
    path('profile/', include('profiles.urls', namespace='profile')),
    path('gallery/', include('galleries.urls', namespace='gallery'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from profiles.views import ProfileDashboardView

app_name = 'profiles'

urlpatterns = [
    path('', ProfileDashboardView.as_view(), name='dashboard'),
]

templates/base.html
{% load staticfiles i18n %}

<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>{% trans "Image Vision" %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/loaders.css' %}" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" rel="stylesheet">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        <a href="/" class="logo my-0 mr-md-auto"><i class="fas fa-camera"></i></a>
        <nav class="my-2 my-md-0 mr-md-3">
        </nav>
        {% if request.user.is_authenticated %}
            <nav class="my-2 my-md-0 mr-md-3">
                <a class="p-2 text-dark" href="{% url 'profile:dashboard' %}">Panel</a>
            </nav>
            <span class="current-user mr-md-3 mx-md-3">{{ request.user }}</span>
            <a class="btn btn-outline-primary" href="{% url 'logout' %}">{% trans "Wyloguj" %}</a>
        {% else %}
            <a class="btn btn-outline-primary" href="{% url 'login' %}">{% trans "Zaloguj się" %}</a>
        {% endif %}
    </div>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            <div class="msg-content">{{ message }}</div>
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="container">
    {% block content %}

    {% endblock %}
    </div>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="#">{% trans "Do góry" %}</a>
            </p>
            <p>Image Vision &copy; 2018</p>
        </div>
    </footer>

    <script src="{% static 'plugins/jquery/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block content %}

<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center page-wrapper">
    <h1 class="display-4">{% trans "Image Vision" %}</h1>
    <p class="lead">
        {% trans "Zarejestruj się, dodaj swoje zdjęcia i przekonaj się jak komputery rozpoznają elementy znajdujące się na nich" %}
    </p>
    <div class="mt-5">
        <a href="{% url 'registration' %}" class="btn btn-primary my-2">{% trans "Zarejestruj się" %}</a>
    </div>
</div>

{% endblock %}

{% block extra_js %}
{% endblock %}